version: '3.1'
services:
  anklet:
    build:
      context: ./
      dockerfile: Dockerfile
    # image: veertu/anklet:latest
    container_name: anklet
    volumes:
      - /Users/nathanpierce/.config/anklet:/root/.config/anklet/
    ports: 
      - "8081:8081"
    environment:
      # - LOG_LEVEL=dev
      - ANKLET_CONFIG_FILE_NAME=controller-config.yml
      # AGGREGATOR ###################################################
      # - ANKLET_METRICS_AGGREGATOR=true
      # - ANKLET_METRICS_PORT=8081 
      # - ANKLET_METRICS_URLS=http://host.docker.internal:8080/metrics # comma separation for multiple urls
      # - ANKLET_METRICS_SLEEP_INTERVAL=10
      # - ANKLET_METRICS_DATABASE_ENABLED=true
      # - ANKLET_METRICS_DATABASE_URL=host.docker.internal
      # - ANKLET_METRICS_DATABASE_PORT=6379
      # - ANKLET_METRICS_DATABASE_USER=
      # - ANKLET_METRICS_DATABASE_PASSWORD=
      # - ANKLET_METRICS_DATABASE_DATABASE=0

