name: Build Artifacts

on:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - run: git tag $(cat VERSION) || [[ $? -eq 128 ]] && true || exit 1
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1
          cache: false
      - name: Run GoReleaser build
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: goreleaser-archive
            path: dist/*
            retention-days: 1