name: ' [CI TEST] test name with brackets and space'
on:
  workflow_dispatch:

jobs:
  t2-6c14r-2:
    runs-on: [ 
      "${{ github.run_id }}-${{ strategy.job-index }}",
      "anka-template:84266873-da90-4e0d-903b-ed0233471f9f", 
      "anka-template-tag:6c14r",
    ]
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -laht
          sw_vers
          hostname
          echo "123"
          sysctl -n hw.ncpu
      - run: whoami
